[2025-06-09 14:44:41] Starting workflow...
[2025-06-09 14:44:41] Running: endpoint_dataset_issue_type_summary.py
[2025-06-09 14:44:42] SUCCESS: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-09 14:44:42] Running: endpoints_missing_doc_urls.py
[2025-06-09 14:44:44] SUCCESS: .\scripts\endpoints_missing_doc_urls.py
[2025-06-09 14:44:44] Running: generate_odp_issues_csv.py
[2025-06-09 14:44:45] SUCCESS: .\scripts\generate_odp_issues_csv.py
[2025-06-09 14:44:45] Running: generate_odp_status_csv.py
[2025-06-09 14:44:46] SUCCESS: .\scripts\generate_odp_status_csv.py
[2025-06-09 14:44:46] Running: logs_by_week.py
[2025-06-09 14:44:47] SUCCESS: .\scripts\logs_by_week.py
[2025-06-09 14:44:47] Running: operational_issues.py
[2025-06-09 14:44:48] SUCCESS: .\scripts\operational_issues.py
[2025-06-09 14:44:48] Workflow complete.
[2025-06-09 14:45:16] Starting workflow...
[2025-06-09 14:45:16] Running: endpoint_dataset_issue_type_summary.py
[2025-06-09 14:45:17] SUCCESS: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-09 14:45:17] Running: endpoints_missing_doc_urls.py
[2025-06-09 14:46:14] Starting workflow...
[2025-06-09 14:46:14] Running: endpoint_dataset_issue_type_summary.py
[2025-06-09 14:46:14] FAIL: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-09 14:46:14] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\endpoint_dataset_issue_type_summary.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-06-09 14:46:14] Running: endpoints_missing_doc_urls.py
[2025-06-09 14:46:14] FAIL: .\scripts\endpoints_missing_doc_urls.py
[2025-06-09 14:46:14] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\endpoints_missing_doc_urls.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2025-06-09 14:46:14] Running: generate_odp_issues_csv.py
[2025-06-09 14:46:14] FAIL: .\scripts\generate_odp_issues_csv.py
[2025-06-09 14:46:14] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\generate_odp_issues_csv.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-06-09 14:46:14] Running: generate_odp_status_csv.py
[2025-06-09 14:46:14] FAIL: .\scripts\generate_odp_status_csv.py
[2025-06-09 14:46:14] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\generate_odp_status_csv.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-06-09 14:46:14] Running: logs_by_week.py
[2025-06-09 14:46:14] FAIL: .\scripts\logs_by_week.py
[2025-06-09 14:46:14] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\logs_by_week.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2025-06-09 14:46:14] Running: operational_issues.py
[2025-06-09 14:46:14] FAIL: .\scripts\operational_issues.py
[2025-06-09 14:46:14] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\operational_issues.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2025-06-09 14:46:14] Workflow complete.
[2025-06-09 14:46:31] Starting workflow...
[2025-06-09 14:46:31] Running: endpoint_dataset_issue_type_summary.py
[2025-06-09 14:46:35] SUCCESS: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-09 14:46:35] Running: endpoints_missing_doc_urls.py
[2025-06-09 14:46:37] SUCCESS: .\scripts\endpoints_missing_doc_urls.py
[2025-06-09 14:46:37] Running: generate_odp_issues_csv.py
[2025-06-09 14:46:37] SUCCESS: .\scripts\generate_odp_issues_csv.py
[2025-06-09 14:46:37] Running: generate_odp_status_csv.py
[2025-06-09 14:46:39] SUCCESS: .\scripts\generate_odp_status_csv.py
[2025-06-09 14:46:39] Running: logs_by_week.py
[2025-06-09 14:46:40] SUCCESS: .\scripts\logs_by_week.py
[2025-06-09 14:46:40] Running: operational_issues.py
[2025-06-09 14:46:40] SUCCESS: .\scripts\operational_issues.py
[2025-06-09 14:46:40] Workflow complete.
[2025-06-10 15:37:39] Starting workflow...
[2025-06-10 15:37:39] Running: endpoint_dataset_issue_type_summary.py
[2025-06-10 15:37:42] SUCCESS: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-10 15:37:42] Running: endpoints_missing_doc_urls.py
[2025-06-10 15:37:46] SUCCESS: .\scripts\endpoints_missing_doc_urls.py
[2025-06-10 15:37:46] Running: generate_odp_conformance_csv.py
[2025-06-10 15:37:47] SUCCESS: .\scripts\generate_odp_conformance_csv.py
[2025-06-10 15:37:47] Running: generate_odp_issues_csv.py
[2025-06-10 15:37:48] SUCCESS: .\scripts\generate_odp_issues_csv.py
[2025-06-10 15:37:48] Running: generate_odp_status_csv.py
[2025-06-10 15:37:50] SUCCESS: .\scripts\generate_odp_status_csv.py
[2025-06-10 15:37:50] Running: logs_by_week.py
[2025-06-10 15:37:53] SUCCESS: .\scripts\logs_by_week.py
[2025-06-10 15:37:53] Running: operational_issues.py
[2025-06-10 15:38:03] SUCCESS: .\scripts\operational_issues.py
[2025-06-10 15:38:03] Workflow complete.
[2025-06-10 15:38:57] Starting workflow...
[2025-06-10 15:38:57] Running: endpoint_dataset_issue_type_summary.py
[2025-06-10 15:38:58] SUCCESS: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-10 15:38:58] Running: endpoints_missing_doc_urls.py
[2025-06-10 15:38:59] SUCCESS: .\scripts\endpoints_missing_doc_urls.py
[2025-06-10 15:38:59] Running: generate_odp_conformance_csv.py
[2025-06-10 15:39:01] SUCCESS: .\scripts\generate_odp_conformance_csv.py
[2025-06-10 15:39:01] Running: generate_odp_issues_csv.py
[2025-06-10 15:39:02] SUCCESS: .\scripts\generate_odp_issues_csv.py
[2025-06-10 15:39:02] Running: generate_odp_status_csv.py
[2025-06-10 15:39:03] SUCCESS: .\scripts\generate_odp_status_csv.py
[2025-06-10 15:39:03] Running: logs_by_week.py
[2025-06-10 15:39:04] SUCCESS: .\scripts\logs_by_week.py
[2025-06-10 15:39:04] Running: operational_issues.py
[2025-06-10 15:39:05] SUCCESS: .\scripts\operational_issues.py
[2025-06-10 15:39:05] Workflow complete.
[2025-06-11 09:09:35] Starting workflow...
[2025-06-11 09:09:35] Running: endpoint_dataset_issue_type_summary.py
[2025-06-11 09:09:35] FAIL: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-11 09:09:35] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\endpoint_dataset_issue_type_summary.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-06-11 09:09:35] Running: endpoints_missing_doc_urls.py
[2025-06-11 09:09:35] FAIL: .\scripts\endpoints_missing_doc_urls.py
[2025-06-11 09:09:35] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\endpoints_missing_doc_urls.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2025-06-11 09:09:35] Running: generate_odp_conformance_csv.py
[2025-06-11 09:09:35] FAIL: .\scripts\generate_odp_conformance_csv.py
[2025-06-11 09:09:35] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\generate_odp_conformance_csv.py", line 9, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
[2025-06-11 09:09:35] Running: generate_odp_issues_csv.py
[2025-06-11 09:09:35] FAIL: .\scripts\generate_odp_issues_csv.py
[2025-06-11 09:09:35] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\generate_odp_issues_csv.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-06-11 09:09:35] Running: generate_odp_status_csv.py
[2025-06-11 09:09:35] FAIL: .\scripts\generate_odp_status_csv.py
[2025-06-11 09:09:35] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\generate_odp_status_csv.py", line 2, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2025-06-11 09:09:35] Running: logs_by_week.py
[2025-06-11 09:09:35] FAIL: .\scripts\logs_by_week.py
[2025-06-11 09:09:35] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\logs_by_week.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2025-06-11 09:09:35] Running: operational_issues.py
[2025-06-11 09:09:35] FAIL: .\scripts\operational_issues.py
[2025-06-11 09:09:35] Error:
Traceback (most recent call last):
  File "C:\Users\DanielGodden\Documents\MCHLG\collecting_and_managing_data\scripts\operational_issues.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[2025-06-11 09:09:35] Workflow complete.
[2025-06-11 09:13:49] Starting workflow...
[2025-06-11 09:13:49] Running: endpoint_dataset_issue_type_summary.py
[2025-06-11 09:13:55] SUCCESS: .\scripts\endpoint_dataset_issue_type_summary.py
[2025-06-11 09:13:55] Running: endpoints_missing_doc_urls.py
[2025-06-11 09:13:57] SUCCESS: .\scripts\endpoints_missing_doc_urls.py
[2025-06-11 09:13:57] Running: generate_odp_conformance_csv.py
[2025-06-11 09:13:59] SUCCESS: .\scripts\generate_odp_conformance_csv.py
[2025-06-11 09:13:59] Running: generate_odp_issues_csv.py
[2025-06-11 09:14:00] SUCCESS: .\scripts\generate_odp_issues_csv.py
[2025-06-11 09:14:00] Running: generate_odp_status_csv.py
[2025-06-11 09:14:01] SUCCESS: .\scripts\generate_odp_status_csv.py
[2025-06-11 09:14:01] Running: logs_by_week.py
[2025-06-11 09:14:04] SUCCESS: .\scripts\logs_by_week.py
[2025-06-11 09:14:04] Running: operational_issues.py
[2025-06-11 09:14:12] SUCCESS: .\scripts\operational_issues.py
[2025-06-11 09:14:12] Workflow complete.
